spring:
  application:
    name: rohitfi-backend
  profiles:
    active: local

#THIS: Delays creating beans until they are actually needed
main:
  lazy-initialization: true

  # --- RELATIONAL DATABASE (POSTGRESQL) ---
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
        format_sql: true

  # --- DOCUMENT DATABASE (MONGODB) ---
  data:
    mongodb:
      uri: ${MONGO_URI}

  # --- BASIC SECURITY ---
  security:
    user:
      name: admin
      password: ${ADMIN_PASS:admin123}

server:
  port: ${PORT:8080}

# --- CUSTOM APPLICATION PROPERTIES ---
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

# --- BREVO CONFIGURATION ---
brevo:
  api-key: ${BREVO_API_KEY:}
  sender-email: ${BREVO_SENDER_EMAIL:rohitkadufreelance@gmail.com}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.rohitfi: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN