package com.rohitfi.common.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HomeController {

    @GetMapping(value = "/", produces = "text/html")
    public String home() {
        return "<!doctype html>"
                + "<html lang=\"en\">"
                + "<head>"
                + "  <meta charset=\"utf-8\">"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
                + "  <title>RoHitFi Digital Banking API</title>"
                + "  <style>"
                + "    :root{--bg:#0f172a;--card:#0b1220;--muted:#94a3b8;--accent1:#7c3aed;--accent2:#06b6d4;--glass:rgba(255,255,255,0.04)}"
                + "    html,body{height:100%;margin:0;font-family:Inter,Segoe UI,Roboto,Arial,sans-serif;background:linear-gradient(180deg,#071029 0%, #071a2a 100%);color:#e6eef8}"
                + "    .wrap{min-height:100%;display:flex;align-items:center;justify-content:center;padding:40px}"
                + "    .card{width:100%;max-width:980px;background:linear-gradient(180deg, rgba(255,255,255,0.02), rgba(255,255,255,0.01));border-radius:14px;padding:28px;box-shadow:0 10px 30px rgba(2,6,23,0.6);backdrop-filter:blur(6px);border:1px solid rgba(255,255,255,0.03)}"
                + "    .header{display:flex;align-items:center;gap:16px}"
                + "    .logo{width:64px;height:64px;border-radius:12px;display:flex;align-items:center;justify-content:center;font-weight:800;color:white;background:linear-gradient(135deg,var(--accent1),var(--accent2));font-size:20px;box-shadow:0 6px 18px rgba(12,18,40,0.6)}"
                + "    .title{font-size:20px;font-weight:700;margin:0;color:#f8fafc}"
                + "    .subtitle{margin:2px 0 0 0;color:var(--muted);font-size:13px}"
                + "    .grid{display:grid;grid-template-columns:1fr 320px;gap:20px;margin-top:20px}"
                + "    .main{padding:18px;border-radius:12px;background:linear-gradient(180deg, rgba(255,255,255,0.01), rgba(255,255,255,0.00));border:1px solid var(--glass)}"
                + "    .status{display:flex;align-items:center;gap:10px;font-weight:600}"
                + "    .dot{width:12px;height:12px;border-radius:50%;background:#10b981;box-shadow:0 6px 18px rgba(16,185,129,0.12)}"
                + "    .desc{color:var(--muted);margin-top:8px;font-size:14px;line-height:1.45}"
                + "    .links{display:flex;gap:10px;margin-top:16px;flex-wrap:wrap}"
                + "    .btn{display:inline-flex;align-items:center;gap:8px;padding:10px 14px;border-radius:10px;text-decoration:none;font-weight:700;font-size:13px;border:1px solid rgba(255,255,255,0.04)}"
                + "    .btn-primary{background:linear-gradient(90deg,var(--accent1),var(--accent2));color:white;box-shadow:0 8px 24px rgba(12,18,40,0.5)}"
                + "    .btn-ghost{background:transparent;color:#cfe8ff;border:1px solid rgba(255,255,255,0.04)}"
                + "    .meta{margin-top:18px;display:flex;flex-direction:column;gap:8px;color:var(--muted);font-size:13px}"
                + "    .side{padding:18px;border-radius:12px;background:linear-gradient(180deg, rgba(255,255,255,0.01), rgba(255,255,255,0.00));border:1px solid var(--glass);display:flex;flex-direction:column;gap:12px}"
                + "    .card-item{padding:12px;border-radius:10px;background:linear-gradient(180deg, rgba(255,255,255,0.01), rgba(255,255,255,0.00));border:1px solid rgba(255,255,255,0.02)}"
                + "    .small{font-size:12px;color:var(--muted)}"
                + "    footer{margin-top:18px;text-align:center;color:var(--muted);font-size:12px}"
                + "    @media (max-width:880px){.grid{grid-template-columns:1fr;}.logo{width:56px;height:56px}.card{padding:18px}}"
                + "  </style>"
                + "</head>"
                + "<body>"
                + "  <div class=\"wrap\">"
                + "    <div class=\"card\">"
                + "      <div class=\"header\">"
                + "        <div class=\"logo\">RF</div>"
                + "        <div>"
                + "          <div class=\"title\">RoHitFi Digital Banking API</div>"
                + "          <div class=\"subtitle\">Core backend · microservices online · secure fintech primitives</div>"
                + "        </div>"
                + "      </div>"
                + ""
                + "      <div class=\"grid\">"
                + "        <div class=\"main\">"
                + "          <div class=\"status\"><span class=\"dot\"></span> <span>System Online</span></div>"
                + "          <div class=\"desc\">Welcome to the backend API of the RoHitFi Digital Banking Platform. All microservices are active and accepting connections. Use the links to explore the API surface or inspect OpenAPI JSON.</div>"
                + ""
                + "          <div class=\"links\">"
                + "            <a class=\"btn btn-primary\" href=\"/swagger-ui.html\" target=\"_blank\" rel=\"noopener\">📚 Open Swagger UI</a>"
                + "            <a class=\"btn btn-ghost\" href=\"/v3/api-docs\" target=\"_blank\" rel=\"noopener\">⚙️ View OpenAPI JSON</a>"
                + "            <a class=\"btn btn-ghost\" href=\"/health\" target=\"_blank\" rel=\"noopener\">🩺 Health</a>"
                + "            <a class=\"btn btn-ghost\" href=\"/metrics\" target=\"_blank\" rel=\"noopener\">📈 Metrics</a>"
                + "          </div>"
                + ""
                + "          <div class=\"meta\">"
                + "            <div><strong>Environment</strong>: <span class=\"small\">Production / Render</span></div>"
                + "            <div><strong>API Base</strong>: <span class=\"small\">/api/v1</span></div>"
                + "            <div><strong>Docs</strong>: <span class=\"small\">Swagger UI and OpenAPI JSON available</span></div>"
                + "          </div>"
                + "        </div>"
                + ""
                + "        <aside class=\"side\">"
                + "          <div class=\"card-item\">"
                + "            <div style=\"display:flex;justify-content:space-between;align-items:center\">"
                + "              <div><strong>RoHitFi Core Banking</strong></div>"
                + "              <div class=\"small\">v1.0.0</div>"
                + "            </div>"
                + "            <div class=\"small\" style=\"margin-top:8px\">Stable · API-first · Secure by design</div>"
                + "          </div>"
                + ""
                + "          <div class=\"card-item\">"
                + "            <div style=\"display:flex;justify-content:space-between;align-items:center\">"
                + "              <div><strong>Last Deploy</strong></div>"
                + "              <div class=\"small\">just now</div>"
                + "            </div>"
                + "            <div class=\"small\" style=\"margin-top:8px\">Commit: <code style=\"color:#cfe8ff;background:transparent;border-radius:4px;padding:2px 6px\">abcdef1</code></div>"
                + "          </div>"
                + ""
                + "          <div class=\"card-item\">"
                + "            <div style=\"display:flex;justify-content:space-between;align-items:center\">"
                + "              <div><strong>Support</strong></div>"
                + "              <div class=\"small\">support@rohitfi.com</div>"
                + "            </div>"
                + "            <div class=\"small\" style=\"margin-top:8px\">For infra or API access requests, contact the platform team.</div>"
                + "          </div>"
                + "        </aside>"
                + "      </div>"
                + ""
                + "      <footer>© " + java.time.Year.now().getValue() + " RoHitFi Digital Banking — Built with care</footer>"
                + "    </div>"
                + "  </div>"
                + "</body>"
                + "</html>";
    }
}
